# Generated by Django 5.0.3 on 2024-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_krsteni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knjiga', models.CharField(max_length=100)),
                ('strana', models.CharField(max_length=1000)),
                ('broj', models.CharField(max_length=100000)),
                ('eparhija', models.CharField(max_length=100)),
                ('hram', models.CharField(max_length=100)),
                ('mjesto', models.CharField(max_length=30)),
                ('godina', models.CharField(max_length=2)),
                ('datum_rodjenja', models.CharField(max_length=100)),
                ('mjesto_rodjenja', models.CharField(max_length=30)),
            ],
        ),
    ]
